export const GET_HOME_PENDING = "GET_HOME_PENDING";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_HOME_FAILED = "GET_HOME_FAILED";

export const GET_REPO_PENDING = "GET_REPO_PENDING";
export const GET_REPO_SUCCESS = "GET_REPO_SUCCESS";
export const GET_REPO_FAILED = "GET_REPO_FAILED";
